<?php $this->layout = 'default'; ?>
<div class="container">

   <div class="page-header">
      <h1>Este é o <i><strong>Base</strong> Framework MVC</i></h1>
   </div>

   <div class="row">
      <div class="col-md-7 col-sm-6 col-xs-12 text-justify">
         <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis praesentium, reprehenderit beatae molestias? Delectus modi dolores reprehenderit, et est nulla repellat. Minima nesciunt ducimus deserunt aperiam corporis, debitis similique fuga.
            Voluptate nostrum, sint natus inventore, voluptates vel omnis iure eligendi facilis, in quod iste labore. Facilis aperiam commodi illum? Quos deserunt sed quidem eaque tempora veritatis perferendis quod delectus accusantium!
         </p>
         <p>
            Mollitia aspernatur fugiat numquam perferendis, voluptates vel omnis iure ducimus maxime unde nesciunt, vel rem deleniti voluptas hic doloremque sequi sapiente est minus nam modi eligendi porro tenetur ut, fugit incidunt eos velit debitis.
            Unde magni veritatis, natus optio ex dignissimos at eius reprehenderit sequi, placeat enim similique nobis corporis culpa, ea voluptates sit esse dolor aspernatur. Reiciendis, veniam ducimus quis, perspiciatis corrupti ducimus deserunt aperiam corporis dolore! 
         </p>
      </div>
      <div class="col-md-5 col-sm-6 col-xs-12">
         <?=$this->view('commons/login-form')?>
      </div>
   </div>

</div>