<?php $this->layout = 'default'; ?>
<div class="container">
   <div class="page-header">
      <h1>Oops! Erro 404</h1>
   </div>
   <div class="row">
      <div class="col-xs-12">
         <p>
            O endereço solicitado não foi encontrado em nosso servidor. <br><br>
            Verifique se o endereço <code><?=$url?></code> informado está correto. 
         </p>
      </div>
   </div>
</div>