<?=$head?>
<?=$menu?>
<div class="container">
   <div class="page-header">
      <h1>Oops! Erro 404</h1>
   </div>
   <div class="row">
      <div class="col-xs-12">
         <p>
            O endereço solicitado não foi encontrado em nosso servidor. 
            Verifique se o endereço foi digitado corretamente. 
         </p>
         <?php
            if (!empty($error)){
         ?>
            <h4>Detalhes:</h4>
            <p><?=$error?></p>
         <?php
            }
         ?>
      </div>
   </div>
</div>
<?=$footer?> 